//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjdemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class 學生選課資料
    {
        [DisplayName("學號")]
        public string STUD_NO { get; set; }
        [DisplayName("課程年度")]
        public string ACAD_YEAR { get; set; }
        
        public string SEME_TYPE { get; set; }
        [DisplayName("課號")]
        public string COURSE_NO { get; set; }
    }
}
