//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjdemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class 學生學籍資料
    {

        [DisplayName("學號")]
        public string STUD_NO { get; set; }
        [DisplayName("姓名")]
        public string STUD_NAME { get; set; }
        [DisplayName("性別")]
        public string SEX { get; set; }
        [DisplayName("科系")]
        public string DEPT_CODE { get; set; }
        [DisplayName("電話")]
        public string TEL { get; set; }
        [DisplayName("地址")]
        public string ADDRESS { get; set; }
    }
}
