//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjdemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class 系所資料
    {
        public string DEPT_CODE { get; set; }
        [DisplayName("系所中文名稱")]
        public string DEPT_NAME { get; set; }
        public string DEPT_NAME_ENG { get; set; }
    }
}
